version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: "mc-server"
    ports:
      - "25565:25565"
    volumes:
      - ${MINECRAFT_DATA_PATH:-./data}:/data
    environment:
      EULA: "TRUE"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "8G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "iambill42362really"
      VERSION: "1.17.1"
    restart: unless-stopped
  rcon:
    image: itzg/rcon
    container_name: "rcon-web-admin"
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - ${RCON_DATA_PATH:-./rcon-data}:/opt/rcon-web-admin/db
    depends_on:
      - minecraft
    # environment:
    #   RWA_USERNAME: admin
    #   RWA_PASSWORD: admin
    #   RWA_ADMIN: "TRUE"
    #   # is referring to the service name 'mc' declared below
    #   RWA_RCON_HOST: mc
    #   # needs to match the password configured for the container, see RCON_PASSWORD below
    #   RWA_RCON_PASSWORD: "iambill42362really"

  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    container_name: "mc-backup"
    volumes:
      - ./data:/mcdata:ro
      - ./backups:/backups
    depends_on:
      - minecraft
    restart: unless-stopped

volumes:
  backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backups
