version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: "mc"
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "8G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "iambill42362really"
      VERSION: "1.17.1"
    # restart: always
  rcon:
    image: itzg/rcon
    container_name: "rcon"
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "./rcon-data:/opt/rcon-web-admin/db"
